version: '3.2'

services:
    hbm_php:
        container_name: hbm_php
        build: ./php
        environment:
            - DB_INFRA_PORT_5432_TCP_ADDR=hbm_db
            - DB_INFRA_PORT_5432_TCP_PORT=5432
            - DB_INFRA_USER=postgres
            - DB_INFRA_PASSWORD=postgres
            - DB_INFRA_NAME=postgres
            - WS_INFRA_PORT_8080_TCP_ADDR=ws
            - WS_INFRA_PORT_8080_TCP_PORT=8080
            - PLANNER_URL=http://localhost/
        volumes:
            - type: volume
              source: C:\projects\xbt1\homebyme\byme_web\cms\byme
              name: hbm_web
              target: /var/www/html
        links:
            - hbm_db
            - hbm_memcached
    hbm_web:
        container_name: hbm_web
        build: ./web
        volumes:
            - type: volume
              source: C:\projects\xbt1\homebyme\byme_web\cms\byme
              name: hbm_web
              target: /var/www/html
        links:
            - hbm_php
        ports:
            - 1282:80
    hbm_db:
        container_name: hbm_db
        build: ./db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 1254:5432
    hbm_ws:
        container_name: hbm_ws
        build: ./ws
        volumes:
            - type: bind
              source: C:\projects\xbt1\homebyme\byme_server\build\docker\infra.by.me\ws
              target: /var/node
        #links:
        #    - hbm_php
        ports:
            - 1280:80

    hbm_memcached:
        container_name: hbm_memcached
        image: memcached:alpine
        ports:
            - 12211:11211

    hbm_redis:
        container_name: hbm_redis
        image: redis:alpine
        #links:
        #    - hbm_ws

volumes:
    hbm_web:
    #hbm_ws:
